export const demoBook = {
  id: 'demo-book-1',
  title: 'The Future of AI',
  description: 'A comprehensive guide exploring artificial intelligence, its applications, and impact on society.',
  coverImage: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date(),
  chapters: [
    {
      id: 'demo-chapter-1',
      bookId: 'demo-book-1',
      title: 'Introduction to AI',
      order: 0,
      layoutType: 'chapter',
      content: null,
      imageUrl: null,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
      sections: [
        {
          id: 'demo-section-1',
          chapterId: 'demo-chapter-1',
          mainPoint: 'What is Artificial Intelligence?',
          content: 'Artificial Intelligence (AI) represents one of the most transformative technologies of our time. At its core, AI refers to computer systems designed to perform tasks that typically require human intelligence. These tasks include learning from experience, recognizing patterns, understanding language, and making decisions.\n\nThe field of AI has evolved significantly since its inception in the 1950s. Today, AI powers everything from virtual assistants on our phones to recommendation systems on streaming platforms. Modern AI systems use machine learning algorithms that can analyze vast amounts of data and improve their performance over time without being explicitly programmed for every scenario.',
          order: 0,
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
        {
          id: 'demo-section-2',
          chapterId: 'demo-chapter-1',
          mainPoint: 'Brief History of AI Development',
          content: 'The journey of artificial intelligence began in the mid-20th century when pioneers like Alan Turing posed the fundamental question: "Can machines think?" The term "artificial intelligence" was coined in 1956 at the Dartmouth Conference, marking the official birth of AI as a field of study.\n\nThe decades that followed saw periods of great optimism followed by "AI winters" - times when progress stalled and funding dried up. However, the 21st century has witnessed an AI renaissance, driven by three key factors: exponential growth in computing power, availability of massive datasets, and breakthroughs in deep learning algorithms.',
          order: 1,
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
        {
          id: 'demo-section-3',
          chapterId: 'demo-chapter-1',
          mainPoint: 'Why AI Matters Today',
          content: null,
          order: 2,
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
      ],
    },
    {
      id: 'demo-chapter-2',
      bookId: 'demo-book-1',
      title: 'Machine Learning Fundamentals',
      order: 1,
      layoutType: 'chapter',
      content: null,
      imageUrl: null,
      createdAt: new Date('2024-01-02'),
      updatedAt: new Date(),
      sections: [
        {
          id: 'demo-section-4',
          chapterId: 'demo-chapter-2',
          mainPoint: 'Understanding Machine Learning',
          content: 'Machine learning is a subset of AI that focuses on creating systems that can learn and improve from experience. Unlike traditional programming where developers write explicit instructions, machine learning algorithms identify patterns in data and make predictions or decisions based on those patterns.\n\nThere are three main types of machine learning: supervised learning (learning from labeled data), unsupervised learning (finding patterns in unlabeled data), and reinforcement learning (learning through trial and error with rewards and penalties).',
          order: 0,
          createdAt: new Date('2024-01-02'),
          updatedAt: new Date(),
        },
      ],
    },
    {
      id: 'demo-chapter-3',
      bookId: 'demo-book-1',
      title: 'Real-World Applications',
      order: 2,
      layoutType: 'chapter',
      content: null,
      imageUrl: null,
      createdAt: new Date('2024-01-03'),
      updatedAt: new Date(),
      sections: [],
    },
  ],
};
